### ISSUE TITLE
wss connection issue with tubesock

### ISSUE THREAD

**Issue by daupawar** [delight-im/Android-DDP#101]
When i was trying to connect Secure layer with `wss://myurl/websocket` i am getting `Meteor Exception error while creating secure socket` error 
Same url works with [meteor ios](https://github.com/martijnwalraven/meteor-ios) lib in ios 
so i replaced [tubesock](https://github.com/ngauthier/tubesock) code with [nv-websocket-client](https://github.com/TakahikoKawasaki/nv-websocket-client)  and now its working fine

**Comment by mwaclawek** [comment]
Thanks for your report!

Can you share the URL? Or some other URL where this happens?

Is there any way you can print the complete stack trace and post it here?

Or are you trying to use a self-signed certificate? https://github.com/delight-im/Android-DDP/issues/100

**Comment by mwaclawek** [comment]
It seemed this was due to Server Name Indication (SNI) as part of SSL/TLS, which may not be supported by our WebSocket library. Can someone verify?

**Comment by daupawar** [comment]
SNI is not an issue, 'nv-websocket-client' works well where  'tubesock' cant

**Comment by mwaclawek** [comment]
Yes, presumably because "nv-websocket-client" *does* support SNI :)

We'll offer a version of this library with ["nv-websocket-client"](https://github.com/TakahikoKawasaki/nv-websocket-client) instead of ["TubeSock"](https://github.com/firebase/TubeSock) in a separate branch so that everybody can test it and see if it works better.

**Comment by musriabhijit** [comment]
com.firebase.tubesock.WebSocketException: error while creating secure socket  i am getting this exception while connecting my websocket  so what is the solution

**Comment by daupawar** [comment]
@musriabhijit   please  send your connection URL and code

**Comment by musriabhijit** [comment]
in the sample code i am just changing my web socket with http://ec2-50-17-2-110.compute-1.amazonaws.com:3000/ so this is my url

**Comment by mwaclawek** [comment]
@musriabhijit Can you try changing `http://` to `ws://` at the beginning? And are you sure you don't need `/websocket` instead of `/` at the end? By the way, I can't connect to your site using [this online tool](http://software.hixie.ch/utilities/js/websocket/) so there might be some problem on your server.

**Comment by musriabhijit** [comment]
ya i got it and i am able to connect with it the web socket now and i wanted to know  to send the data back to socket because we are not using the json to send the data back

**Comment by musriabhijit** [comment]
if  i use wss it is going to exception and disconnected so what is the solution for this

**Comment by musriabhijit** [comment]
@ daupawar i am also facing the same  Issue  as mention by you at first When i was trying to connect Secure layer with wss://myurl/websocket i am getting Meteor Exception error while creating secure socket error 
Same url works with meteor ios lib in ios 
so i replaced tubesock code with nv-websocket-client and now its working fine
 so how you solved the problem and if you made the library changes to the current library  can you send that library

**Comment by daupawar** [comment]
@musriabhijit  I haven't made library, i downloaded whole code and changed build.gradle for nv-websocket. then i changed meteor.java file.

**Comment by daupawar** [comment]
@musriabhijit  send me your mail id

**Comment by musriabhijit** [comment]
@daupawar  musri.abhijit007@gmail.com

**Comment by ocram** [comment]
To sum up, we've found out that [TubeSock](https://github.com/firebase/TubeSock), which has been the underlying WebSocket component for this library, doesn't seem to support Server Name Indication (SNI) or [self-signed certificates](https://github.com/delight-im/Android-DDP/issues/100) with SSL/TLS.

Thus we decided it may be a good idea to switch to [nv-websocket-client](https://github.com/TakahikoKawasaki/nv-websocket-client), which also proved to have more active support. Since we [heard about it initially](https://github.com/delight-im/Android-DDP/issues/3), that library has always been a promising alternative, but I wanted to watch it a little longer to see whether support for it continues.

Now, let's finally attempt the switch between these two libraries. I've started the transition in https://github.com/delight-im/Android-DDP/commit/ec334366059f030c3ff73b66f154dcf5f333359c but this is an early draft. There may be bugs that we'll have to fix. There are many new possibilities for configuration and customization that we'll be able to use. So that implementation has to be completed and perhaps improved in some existing parts.

If anybody has feedback on this implementation, especially given that some of you have already done this change in their private forks, I'd love to hear what you think.

In order to try the new implementation, it will be sufficient to replace the version `v3.1.2` in your Gradle dependency with the following commit hash:

```
ec334366059f030c3ff73b66f154dcf5f333359c
```

Should you still be interested in this issue, @daupawar, @musriabhijit, @MathiasHH, @elbow, @vlasky, @isdzulqor and anybody else, your feedback will be much appreciated. Thanks!

**Comment by daupawar** [comment]
@ocram  that would be great. I have been using 'nv-websocket-client' in forked code from last 3 months, I tried with different urls ('wss' and 'ws') and haven't found any issue with it.

**Comment by ocram** [comment]
Oh, let's keep this open for now :)

As explained above, I have changed the WebSocket library in this project as well. So hopefully, everyone can soon use this repository instead of their private forks again.

For that to happen, I just need some feedback on the implementation. My previous comment explains how the implementation can be tested with your app.

Since some of you have created their private forks, I'd also love to hear about how your code is different from https://github.com/delight-im/Android-DDP/commit/ec334366059f030c3ff73b66f154dcf5f333359c and whether we need some more changes for everything to work correctly, including SSL/TLS with SNI and self-signed certificates.

**Comment by ocram** [comment]
Again, the following is the dependency for those who would like to test this library with the alternative WebSocket library that may replace the existing one:

```
compile 'com.github.delight-im:Android-DDP:ec334366059f030c3ff73b66f154dcf5f333359c'
```

**Comment by shaiamir** [comment]
ws and wss works for me. Thanks!

**Comment by ocram** [comment]
@shaiamir Thanks! This is now in the main branch and in the latest release.

**Comment by deadjdona** [comment]
Good day.

Can you update nv-websocket-client to latest version, please?

**Comment by najeebullahshah** [comment]
I am using a wss one with the following dependency:

compile 'com.github.delight-im:Android-DDP:ec334366059f030c3ff73b66f154dcf5f333359c'

and getting the following exception:

com.neovisionaries.ws.client.WebSocketException: Failed to get the input stream of the raw socket: Connection closed by peer
