### ISSUE TITLE
Switch to GSON

### ISSUE THREAD

**Issue by tomykho** [delight-im/Android-DDP#131]
Is it possible to use GSON instead of Jackson?

**Comment by ocram** [comment]
Thanks for your feedback!

Is there any specific reason why this change should be implemented? Or is it just a personal preference?

**Comment by tomykho** [comment]
Yes, because APK grew bigger when using Jackson.

**Comment by ocram** [comment]
Thanks for explaining the motivation.

We *might* save up to 776.9 KB (*uncompressed*) if GSON was indeed a full replacement for everything that we currently use Jackson for. But since the binary size is not the only consideration, the space saved is not really that much (*compressed* even less) and replacing the implementation takes effort that might be more useful in other places, we won't do this for now. Sorry!
