### ISSUE TITLE
How to keep user logged in?

### ISSUE THREAD

**Issue by iahvector** [delight-im/Android-DDP#15]
How to keep a user logged in or log him automatically without saving his password? I noticed that the login request returns a token. Can't this be used?

**Comment by mwaclawek** [comment]
Yes, that token can be used. Thank you!

The latest version of this library should now support automatic login with the help of that token.

In order to update, please proceed as follows:

 1. Get the [latest JAR](https://github.com/delight-im/Android-DDP/tree/master/Android/JARs) from this repository and include it in your app
 2. Replace all occurrences of `new Meteor(...)` with `new Meteor(this, ...)` in your own code
 3. Replace all occurrences of `void onConnect()` with `void onConnect(final boolean signedInAutomatically)` in your own code
 4. Only perform the login manually if the parameter `signedInAutomatically` is set to `false`

Does that work?

**Comment by iahvector** [comment]
Yes, Thanks.
Can you please add methods to check if a user is logged in, get logged in user ID and logout?

**Comment by mwaclawek** [comment]
@iahvector Please get the updated JAR again and use the methods `mMeteor.isLoggedIn()`, `mMeteor.getUserId()` and `mMeteor.logout()`. Thanks!
