### ISSUE TITLE
Setting callback before openConnection.

### ISSUE THREAD

**Issue by chopikboy** [delight-im/Android-DDP#60]
In constructor we do openConnection at the end. In openConnection (Meteor.java 247) we do mCallbackProxy.onException(e). But what callback can handle this? How I can setCallback before this statement?

**Comment by mwaclawek** [comment]
You're right again, of course :) Thank you!

The backward compatible way would be to add another constructor that takes one more argument (an initial callback class to use):

```java
public Meteor(final Context context, final String serverUri, final String protocolVersion, final DataStore dataStore, MeteorCallback callback)
```

The backward incompatible way would be to remove the call to `openConnection(false)` from the end of the constructor and delay it until a separate (new) `connect` method is called, right?

What do you think?

**Comment by mwaclawek** [comment]
Again, thank you very much!

This [should have been fixed](https://github.com/delight-im/Android-DDP/commit/2a03f9532f82d520d3f1df0894110ca4cf88b897) in the `master` branch now and will be included in the next major release.

In order to test the changes, please temporarily change your Gradle dependency to the following:

`compile 'com.github.delight-im:Android-DDP:2f144b3d77'`

The list of required (breaking) changes [is here](https://github.com/delight-im/Android-DDP/issues/69).
