### ISSUE TITLE
Insert and fetching issue

### ISSUE THREAD

**Issue by prasannakumark** [delight-im/Android-DDP#91]
Hi All,

I am new for meteor, i am try to inserting record from from device it showing queueing...

05-05 07:22:18.208 11706-11706/com.chicks.deliveryboy I/System.out:     message == {"msg":"method","id":"d85cfb9d-b926-4ab7-9d81-ec3bece8810e","params":[{"registered_by_id":"1","address":{"latitude":19.564507191849508,"address":"svvdgsvsvs","address_label":"test","landmark":"wvsvvsvdbd","longitude":19.564507191849508},"mobile":"5555858585","name":"egegdgdve","registered_by":"db","alternate_mobile":["1885848487"],"frequency":"Occasionally","updatedAt":1462413138127,"createdAt":1462413138127}],"method":"/testdatabase/insert"}
05-05 07:22:18.208 11706-11706/com.chicks.deliveryboy I/System.out:     queueing

i do not know why it is occurring like that. some times i can able to insert record(for other meteor project) but some times it showing like this. will meteor will support the 6.0 also?

And also i am not able to fetch the data but still records are available(i checked in browser).

https://friendpaste.com/6A2E1UvEX4h4ZCtNbBZykQ 

Note: i am sure that i started meteor server and all before run the project
What the mistake i might doing here or please suggest me how i can achieve this. If you need any clarifications please let know i can provide that 

Thanks
P Prasanna Kumar

**Comment by mwaclawek** [comment]
Thanks for your question!

As you can see [in the source code](https://github.com/delight-im/Android-DDP/blob/7ee9d8b5eb58253fbcd17062847356efa2100667/Source/library/src/main/java/im/delight/android/ddp/Meteor.java#L320), the only reason why messages might be queued is because the library thinks there is no connection to the server. Can you check this? It seems your WebSocket connection has been closed (either by the client or the server) or you didn't establish a connection in the first place.

Are you referring to Android 6.0 support? I don't see any reason why it shouldn't work (already today) :)

If you want to access the collections and documents in the database (with the `getDatabase` call), you have to *subscribe* to your publications first in order for any data to show up. After that, you are informed about incoming data in the `onDataXxx` callbacks.

**Comment by prasannakumark** [comment]
Thanks for quick reply, yes i tested it will support android 6.0. It was network issue my side once again thank you!!!

**Comment by mwaclawek** [comment]
No problem!
